var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                               xx                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                          oo           xxxx                     ",
   "                                                                                ",
   "  oo                  oooooooo                   xxxxx             o         o  ",
   "  xxx                                  xxx                            o xx x x  ",
   "  x  xx           xxxx     xx!!!xx                                  o xx     x  ",
   "  x    x       xxx          xxxxx                                 o xxx      x  ",
   "  x        xxx                                                    xxx     o  x  ",
   "  x                                                  xx!!!!xxx               x  ",
   "  x  @                                     j   o    xx!!!!!!xxx              x  ",
   "  xmmxxxxxxxxx!!xxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "             xxxx              xxx                                              ",
   "                            xxxx                                                ",
   "   xxxxxxxx               xxx                                                   ",
   "          xxx    b     xxxx                                                     ",
   "             xx oooo xx                                                         ",
   "               xxxxxx                                                           "],
  ["                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                  o   o   o  x!x  ",
   "                                                                                                            xx!x  ",
   "                                                                                              xxxxxxxxxxxxxxx!!x  ",
   "               x!!!x                                                                            !!!!!!!!!!!!!!xx  ",
   "                x|x                                                                       xxxxxx!!!!!!!xxxxxxxx   ",
   "                                                                                      xx v!!!!!!!xxxx             ",
   "                                                                                                                  ",
   "                                                                                 xxx         xxx                  ",
   "                                                                                 x x         x x                  ",
   "                                                    xx                             x        xx                    ",
   "                                               x     x                       xx    x         x                    ",
   "               ooo                             xx    x                             x         x                    ",
   "                    j                          x     x      o oo     x   x         x       xxx                    ",
   "               xxxxxxx        xxx   xxx        x  o  x               x   x      o  x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x o x               x                    ",
   "     @       x         x    xxx x   x          x     x               x   x   x               x                    ",
   "    xxx     xx         x        x   x          x  o  x               x   xxxxx   xxxxxx      x                    ",
   " o  x x      x    oo   x       xx o xx         x     x               x     o     x x         x                    ",
   "xxxxx xxx   xx    oo   x!!!!!!xx     xx!!xxxxxxxx    x!!!!!!!!!!!!!! x     j     x x         x                    ",
   "xxxxx xxx  o xx        xxxxxxxx       xxx            x!!!!!!!xxxxxxxxxxxxxxxxxxxxx xx  o o  xx                    ",
   "    x x!!xxxxx                    o                 xx!!!!!!xx                      xx     xx                     ",
   "xxxxx x!!!!!!x  xx        b                xxxxxxxxxxxxxxxxxx                        xxxxxxx                      ",
   "xxxxx x!!!!!!x                    xxxxxxxxxx!!!!!!xx                                                              ",
   "xxxxx x!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xx                                                              ",
   "xxxxx xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                       ooo                                                    ",
   "                                                  x                                                           ",
   "                                          xxxxxxxxx   xxxxxxxx                                                ",
   "                                         xx           x                                                       ",
   "                                          x           x                                                       ",
   "                                     xx   xx          x                                                       ",
   "                                          x= = = =    x            xxx                                        ",
   "                              xxxx                    x           xxxxx                                       ",
   "                                  xxx          = = = =x   o                 oo                                ",
   "                                     xxxx             x                     xxxxx                             ",
   "                              o   o       x           x|xxxx|  |xxxx|x                                        ",
   "                                          x           x              x                 x!!!x                  ",
   "                             xxx xx   xx xxx     o o  x!!!!!!!!!!!!!!x                  x|x                   ",
   "                             x xxx     xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "  oo                         xx           xx                                         xxx                oo    ",
   "  xxx                         x     x     x                                                              xxx  ",
   "  x x                         x    xxx    x   b                                               xxx        x x  ",
   "  x    xx                     x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x        xx                 x           x                              x oo             o        o       x  ",
   "  x                           xx          x                              x                         xx      x  ",
   "  x           xx                          x       |xxxx|    |xxxx|     xxxxxxxx    oo                      x  ",
   "  x                xxx             o o    x                                        xxx     xx              x  ",
   "  x                           xx          x                                                                x  ",
   "  x                           x    xxx    x                                                     xxx        x  ",
   "  x                           xxxxxxxxxxxxx                                                                x  ",
   "  x      @                    x           x              j                        j              j         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       !  o  !x                                                                                               ",
   "       x     xxx                                                                                              ",
   "       x= o  x  xx                                                                                            ",
   "       x     x    xxxx                                                                                        ",
   "       !  o  !            o                                                                                   ",
   "                                           oo                                     x    x   x x x   x    x     ",
   "          o              xxx               xxx                                     x  x    x   x   x    x     ",
   "                                        xxx                                          x     x   x   x    x     ",
   "                           xxx        xxx                                            x     x x x     xx       ",
   "                                  xxx                                                                         ",
   "                               xxx                                                                            ",
   "                            xxx                                                                               ",
   "                          o                                                                                   ",
   "            xxx  xxx   xxxx      xx                       xx     xx                                           ",
   "                                                                        b   o         o  o   o     o    o     ",
   "      xxx                                                              xx    o       o   o   o o   o    o     ",
   "                    ||||       ||||                              ||           o  o  o    o   o  o  o          ",
   "  xxxxxxxxxxx                                   xxx                      xx    o   o     o   o   o o    o     ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                                    ",
   "  x         x o x       xxxxx       x ox  x               ||                   xxxxx    xxxxxxxxxxxxxxxxxxx   ",
   "  x  @                                                           o                                            ",
   "  xxxxxxx                                     xxxxx  xxxxxxx   xxxx   xxxxxx                                  ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
